name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: setup google-services.json          
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "${GOOGLE_SERVICES_JSON}" >> ./app/google-services.json
      - name: Prepare for build   
        env: 
          MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: |
          chmod +x gradlew
          echo "MAPS_API_KEY=${MAPS_KEY}" >> local.properties       
        
      - name: Build with Gradle
        run: ./gradlew assembleRelease_nominify
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
