name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: GooglerideTracker
  
on: 
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:      
        root-project-path: [./]
        
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Change wrapper permissions
        working-directory: ${{ matrix.root-project-path }}
        run: chmod +x ./gradlew
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2    
      - name: setup google-services.json  
        working-directory: ${{ matrix.root-project-path }}
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "${GOOGLE_SERVICES_JSON}" >> ./app/google-services.json  
      - name: Prepare for build   
        working-directory: ${{ matrix.root-project-path }}
        env: 
          MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}          
        run: |
          echo "MAPS_API_KEY=${MAPS_KEY}" >> local.properties       
      - name: Build Project
        run: ./gradlew build

      - name: Build Release AAB
        run: ./gradlew bundleRelease
      - name: Build with Gradle
        run: ./gradlew assembleRelease_nominify
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
